Repository choongangping/nyami-ref, pull requests merged in 2025-01, with the labels that each got.

#1 🔧 fix[home]: 메인 페이지의 가게 컨테이너 높이 수정
  src/main/resources/static/css/home/homeCategory.css
Labels: pr

#3 ❌ delete: 불필요한 사진 삭제
  src/main/resources/static/images/home/모수.png
Labels: refactor

#14 App.js파일에 수정되지 않은 코드 변경 , 주석처리
  frontend/src/App.js
  frontend/src/features/mypage/Account.jsx
  frontend/src/features/mypage/Activity.jsx
  frontend/src/features/mypage/Profile.jsx
  frontend/src/pages/mypage/MyPage.jsx
Labels: bug, pr

#16 mypage sidebar css 구현
  frontend/package.json
  frontend/src/features/mypage/Activity.jsx
  frontend/src/pages/mypage/MyPage.jsx
  frontend/src/pages/mypage/MyPage.module.css
Labels: pr, feat

#18 App.js 불필요한 경로 삭제 및 Images module 생성 + 로그인페이지 프론트 작업
  backend/src/main/java/com/project/controller/aa
  frontend/src/App.js
  frontend/src/assets/images/google_button.png
  frontend/src/assets/images/index.js
  frontend/src/assets/images/kakao_button.png
  frontend/src/assets/images/naver_button.png
  frontend/src/assets/styles/login/loginCommon.css
  frontend/src/components/button/DuplicateButton.jsx
  frontend/src/components/button/DuplicateButton.module.css
  frontend/src/components/container/Container.js
  frontend/src/components/container/Container.module.css
  frontend/src/components/inputField/InputField.js
  frontend/src/components/inputField/InputField.module.css
  frontend/src/components/select/EmailSelect.jsx
  frontend/src/components/select/EmailSelect.module.css
  frontend/src/pages/login/LoginForm.jsx
  frontend/src/pages/login/LoginForm.module.css
  frontend/src/pages/login/SignUpForm.jsx
  frontend/src/pages/login/SignUpForm.module.css
Labels: pr

#19 mypage 폴더구조 변경(이동)
  frontend/src/App.js
  frontend/src/features/mypage/content/Account.jsx
  frontend/src/features/mypage/content/Account.module.css
  frontend/src/features/mypage/content/Activity.jsx
  frontend/src/features/mypage/content/Activity.module.css
  frontend/src/features/mypage/content/Profile.jsx
  frontend/src/features/mypage/content/Profile.module.css
  frontend/src/features/mypage/sidebar/Sidebar.jsx
  frontend/src/features/mypage/sidebar/Sidebar.module.css
  frontend/src/features/mypage/sidebar/SidebarItem.jsx
  frontend/src/features/mypage/sidebar/SidebarItem.module.css
  frontend/src/pages/mypage/MyPage.jsx
  frontend/src/pages/mypage/MyPage.module.css
Labels: pr, refactor

#20 MyPage 디렉터리 구조 변경
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/layout/Header.jsx
  frontend/src/features/mypage/content/Account.jsx
  frontend/src/features/mypage/content/Account.module.css
  frontend/src/features/mypage/content/Activity.jsx
  frontend/src/features/mypage/content/Activity.module.css
  frontend/src/features/mypage/content/Like.jsx
  frontend/src/features/mypage/content/Like.module.css
  frontend/src/features/mypage/content/Profile.jsx
  frontend/src/features/mypage/content/Profile.module.css
  frontend/src/features/mypage/content/Review.jsx
  frontend/src/features/mypage/content/Review.module.css
  frontend/src/features/mypage/sidebar/Sidebar.jsx
  frontend/src/features/mypage/sidebar/SidebarItem.module.css
  frontend/src/pages/mypage/MyPage.module.css
Labels: pr, refactor

#21 리뷰 초안
  frontend/src/features/mypage/content/Review.jsx
  frontend/src/features/mypage/content/Review.module.css
Labels: pr

#23 페이지 디자인 작업
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/button/Button.jsx
  frontend/src/components/button/Button.module.css
  frontend/src/global.css
  frontend/src/index.js
  frontend/src/pages/Home.jsx
  frontend/src/pages/Home.module.css
  frontend/src/pages/store/StoreDetail.jsx
  frontend/src/pages/store/StoreDetail.module.css
Labels: pr, feat

#24 ID, 비밀번호찾기 디자인
  frontend/src/App.js
  frontend/src/components/button/AuthButton.jsx
  frontend/src/components/button/AuthButton.module.css
  frontend/src/components/button/DuplicateButton.jsx
  frontend/src/components/button/DuplicateButton.module.css
  frontend/src/components/container/Container.module.css
  frontend/src/components/inputField/EmailInputField.jsx
  frontend/src/components/inputField/EmailInputField.module.css
  frontend/src/components/inputField/InputField.js
  frontend/src/components/inputField/InputField.module.css
  frontend/src/components/modal/BasicModal.jsx
  frontend/src/components/modal/BasicModal.module.css
  frontend/src/components/select/EmailSelect.jsx
  frontend/src/components/select/EmailSelect.module.css
  frontend/src/pages/auth/LoginForm.jsx
  frontend/src/pages/auth/LoginForm.module.css
  frontend/src/pages/auth/SignUpForm.jsx
  frontend/src/pages/auth/SignUpForm.module.css
  frontend/src/pages/login/LoginForm.jsx
  frontend/src/pages/login/LoginForm.module.css
  frontend/src/pages/login/SignUpForm.jsx
  frontend/src/pages/login/SignUpForm.module.css
Labels: pr, feat

#28 로그인 화면 수정 및 버튼 컴포넌트 Custom Styles 추가
  frontend/src/components/button/AuthButton.jsx
  frontend/src/components/button/AuthButton.module.css
  frontend/src/components/button/Button.jsx
  frontend/src/components/button/Button.module.css
  frontend/src/components/container/Container.module.css
  frontend/src/components/inputField/EmailInputField.jsx
  frontend/src/components/inputField/EmailInputField.module.css
  frontend/src/components/inputField/InputField.jsx
  frontend/src/components/inputField/InputField.module.css
  frontend/src/components/modal/BasicModal.jsx
  frontend/src/components/modal/BasicModal.module.css
  frontend/src/pages/auth/FindId.jsx
  frontend/src/pages/auth/FindPwd.jsx
  frontend/src/pages/auth/LoginForm.jsx
  frontend/src/pages/auth/LoginForm.module.css
  frontend/src/pages/auth/SignUpForm.jsx
  frontend/src/pages/auth/SignUpForm.module.css
Labels: pr

#29 프로필,계정 정보 핸들러 추가 및 세부 css 구현
  frontend/src/features/mypage/content/Account.jsx
  frontend/src/features/mypage/content/Account.module.css
  frontend/src/features/mypage/content/Profile.jsx
Labels: pr, feat

#30 mypage 프론트 완료
  frontend/src/features/mypage/content/Like.jsx
  frontend/src/features/mypage/content/Review.jsx
Labels: pr, feat

#31 Develop
  frontend/public/index.html
  frontend/src/components/button/Button.module.css
  frontend/src/components/dropdown/BasicDropdown.jsx
  frontend/src/components/dropdown/BasicDropdown.module.css
  frontend/src/components/layout/Header.jsx
  frontend/src/components/layout/Header.module.css
  frontend/src/components/tag/Tag.jsx
  frontend/src/components/tag/Tag.module.css
  frontend/src/features/auth/Login.jsx
  frontend/src/features/auth/Login.module.css
  frontend/src/pages/Home.jsx
  frontend/src/pages/Home.module.css
  frontend/src/pages/auth/LoginForm.jsx
  frontend/src/pages/store/StoreDetail.jsx
Labels: pr, feat
